remote_theme: mmistakes/minimal-mistakes
title: Ace Jones Art & Design
include: ["_pages"]

author:
  name: Ace Jones
  avatar: "/moi.jpg"
  bio: "Professional meme dealer, aspiring artist, complete spazz, and tiny bagel."
